//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public string MaSP { get; set; }
        public string MaHD { get; set; }
        public Nullable<int> SLBan { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
